// Implementation file for parser generated by fsyacc
module Parser
#nowarn "64";; // turn off warnings that type variables used in production annotations are instantiated to concrete type
open FSharp.Text.Lexing
open FSharp.Text.Parsing.ParseHelpers
# 1 "Parser.fsy"

  open AST

# 10 "Parser.fs"
// This type is the type of tokens accepted by the parser
type token = 
  | T_NAT
  | T_ATOM
  | T_PAIR
  | EOF
  | L_PAREN
  | R_PAREN
  | CONS
  | CAR
  | CDR
  | PLUS
  | ADD1
  | CLAIM
  | ZERO
  | DEFINE
  | NAT of (uint32)
  | ATOM of (string)
  | NAME of (string)
// This type is used to give symbolic names to token indexes, useful for error messages
type tokenId = 
    | TOKEN_T_NAT
    | TOKEN_T_ATOM
    | TOKEN_T_PAIR
    | TOKEN_EOF
    | TOKEN_L_PAREN
    | TOKEN_R_PAREN
    | TOKEN_CONS
    | TOKEN_CAR
    | TOKEN_CDR
    | TOKEN_PLUS
    | TOKEN_ADD1
    | TOKEN_CLAIM
    | TOKEN_ZERO
    | TOKEN_DEFINE
    | TOKEN_NAT
    | TOKEN_ATOM
    | TOKEN_NAME
    | TOKEN_end_of_input
    | TOKEN_error
// This type is used to give symbolic names to token indexes, useful for error messages
type nonTerminalId = 
    | NONTERM__startstart
    | NONTERM_start
    | NONTERM_typ
    | NONTERM_value
    | NONTERM_both
    | NONTERM_stmntbody
    | NONTERM_stmnt
    | NONTERM_prog

// This function maps tokens to integer indexes
let tagOfToken (t:token) = 
  match t with
  | T_NAT  -> 0 
  | T_ATOM  -> 1 
  | T_PAIR  -> 2 
  | EOF  -> 3 
  | L_PAREN  -> 4 
  | R_PAREN  -> 5 
  | CONS  -> 6 
  | CAR  -> 7 
  | CDR  -> 8 
  | PLUS  -> 9 
  | ADD1  -> 10 
  | CLAIM  -> 11 
  | ZERO  -> 12 
  | DEFINE  -> 13 
  | NAT _ -> 14 
  | ATOM _ -> 15 
  | NAME _ -> 16 

// This function maps integer indexes to symbolic token ids
let tokenTagToTokenId (tokenIdx:int) = 
  match tokenIdx with
  | 0 -> TOKEN_T_NAT 
  | 1 -> TOKEN_T_ATOM 
  | 2 -> TOKEN_T_PAIR 
  | 3 -> TOKEN_EOF 
  | 4 -> TOKEN_L_PAREN 
  | 5 -> TOKEN_R_PAREN 
  | 6 -> TOKEN_CONS 
  | 7 -> TOKEN_CAR 
  | 8 -> TOKEN_CDR 
  | 9 -> TOKEN_PLUS 
  | 10 -> TOKEN_ADD1 
  | 11 -> TOKEN_CLAIM 
  | 12 -> TOKEN_ZERO 
  | 13 -> TOKEN_DEFINE 
  | 14 -> TOKEN_NAT 
  | 15 -> TOKEN_ATOM 
  | 16 -> TOKEN_NAME 
  | 19 -> TOKEN_end_of_input
  | 17 -> TOKEN_error
  | _ -> failwith "tokenTagToTokenId: bad token"

/// This function maps production indexes returned in syntax errors to strings representing the non terminal that would be produced by that production
let prodIdxToNonTerminal (prodIdx:int) = 
  match prodIdx with
    | 0 -> NONTERM__startstart 
    | 1 -> NONTERM_start 
    | 2 -> NONTERM_typ 
    | 3 -> NONTERM_typ 
    | 4 -> NONTERM_typ 
    | 5 -> NONTERM_value 
    | 6 -> NONTERM_value 
    | 7 -> NONTERM_value 
    | 8 -> NONTERM_both 
    | 9 -> NONTERM_both 
    | 10 -> NONTERM_stmntbody 
    | 11 -> NONTERM_stmntbody 
    | 12 -> NONTERM_stmntbody 
    | 13 -> NONTERM_stmntbody 
    | 14 -> NONTERM_stmntbody 
    | 15 -> NONTERM_stmntbody 
    | 16 -> NONTERM_stmntbody 
    | 17 -> NONTERM_stmntbody 
    | 18 -> NONTERM_stmnt 
    | 19 -> NONTERM_prog 
    | 20 -> NONTERM_prog 
    | _ -> failwith "prodIdxToNonTerminal: bad production index"

let _fsyacc_endOfInputTag = 19 
let _fsyacc_tagOfErrorTerminal = 17

// This function gets the name of a token as a string
let token_to_string (t:token) = 
  match t with 
  | T_NAT  -> "T_NAT" 
  | T_ATOM  -> "T_ATOM" 
  | T_PAIR  -> "T_PAIR" 
  | EOF  -> "EOF" 
  | L_PAREN  -> "L_PAREN" 
  | R_PAREN  -> "R_PAREN" 
  | CONS  -> "CONS" 
  | CAR  -> "CAR" 
  | CDR  -> "CDR" 
  | PLUS  -> "PLUS" 
  | ADD1  -> "ADD1" 
  | CLAIM  -> "CLAIM" 
  | ZERO  -> "ZERO" 
  | DEFINE  -> "DEFINE" 
  | NAT _ -> "NAT" 
  | ATOM _ -> "ATOM" 
  | NAME _ -> "NAME" 

// This function gets the data carried by a token as an object
let _fsyacc_dataOfToken (t:token) = 
  match t with 
  | T_NAT  -> (null : System.Object) 
  | T_ATOM  -> (null : System.Object) 
  | T_PAIR  -> (null : System.Object) 
  | EOF  -> (null : System.Object) 
  | L_PAREN  -> (null : System.Object) 
  | R_PAREN  -> (null : System.Object) 
  | CONS  -> (null : System.Object) 
  | CAR  -> (null : System.Object) 
  | CDR  -> (null : System.Object) 
  | PLUS  -> (null : System.Object) 
  | ADD1  -> (null : System.Object) 
  | CLAIM  -> (null : System.Object) 
  | ZERO  -> (null : System.Object) 
  | DEFINE  -> (null : System.Object) 
  | NAT _fsyacc_x -> Microsoft.FSharp.Core.Operators.box _fsyacc_x 
  | ATOM _fsyacc_x -> Microsoft.FSharp.Core.Operators.box _fsyacc_x 
  | NAME _fsyacc_x -> Microsoft.FSharp.Core.Operators.box _fsyacc_x 
let _fsyacc_gotos = [| 0us; 65535us; 1us; 65535us; 0us; 1us; 3us; 65535us; 5us; 6us; 6us; 7us; 27us; 28us; 9us; 65535us; 14us; 12us; 15us; 12us; 17us; 12us; 19us; 12us; 21us; 12us; 22us; 12us; 24us; 12us; 30us; 12us; 32us; 13us; 8us; 65535us; 14us; 15us; 15us; 16us; 17us; 18us; 19us; 20us; 21us; 22us; 22us; 23us; 24us; 25us; 30us; 31us; 1us; 65535us; 32us; 33us; 10us; 65535us; 0us; 35us; 14us; 11us; 15us; 11us; 17us; 11us; 19us; 11us; 21us; 11us; 22us; 11us; 24us; 11us; 30us; 11us; 35us; 35us; 2us; 65535us; 0us; 2us; 35us; 36us; |]
let _fsyacc_sparseGotoTableRowOffsets = [|0us; 1us; 3us; 7us; 17us; 26us; 28us; 39us; |]
let _fsyacc_stateToProdIdxsTableElements = [| 1us; 0us; 1us; 0us; 1us; 1us; 1us; 2us; 1us; 3us; 1us; 4us; 1us; 4us; 1us; 4us; 1us; 5us; 1us; 6us; 1us; 7us; 1us; 8us; 1us; 9us; 1us; 10us; 1us; 11us; 1us; 11us; 1us; 11us; 1us; 12us; 1us; 12us; 1us; 13us; 1us; 13us; 1us; 14us; 1us; 14us; 1us; 14us; 1us; 15us; 1us; 15us; 1us; 16us; 1us; 16us; 1us; 16us; 1us; 17us; 1us; 17us; 1us; 17us; 1us; 18us; 1us; 18us; 1us; 18us; 1us; 19us; 1us; 19us; 1us; 20us; |]
let _fsyacc_stateToProdIdxsTableRowOffsets = [|0us; 2us; 4us; 6us; 8us; 10us; 12us; 14us; 16us; 18us; 20us; 22us; 24us; 26us; 28us; 30us; 32us; 34us; 36us; 38us; 40us; 42us; 44us; 46us; 48us; 50us; 52us; 54us; 56us; 58us; 60us; 62us; 64us; 66us; 68us; 70us; 72us; 74us; |]
let _fsyacc_action_rows = 38
let _fsyacc_actionTableElements = [|2us; 32768us; 3us; 37us; 4us; 32us; 0us; 49152us; 0us; 16385us; 0us; 16386us; 0us; 16387us; 3us; 32768us; 0us; 3us; 1us; 4us; 2us; 5us; 3us; 32768us; 0us; 3us; 1us; 4us; 2us; 5us; 0us; 16388us; 0us; 16389us; 0us; 16390us; 0us; 16391us; 0us; 16392us; 0us; 16393us; 0us; 16394us; 4us; 32768us; 4us; 32us; 12us; 9us; 14us; 10us; 15us; 8us; 4us; 32768us; 4us; 32us; 12us; 9us; 14us; 10us; 15us; 8us; 0us; 16395us; 4us; 32768us; 4us; 32us; 12us; 9us; 14us; 10us; 15us; 8us; 0us; 16396us; 4us; 32768us; 4us; 32us; 12us; 9us; 14us; 10us; 15us; 8us; 0us; 16397us; 4us; 32768us; 4us; 32us; 12us; 9us; 14us; 10us; 15us; 8us; 4us; 32768us; 4us; 32us; 12us; 9us; 14us; 10us; 15us; 8us; 0us; 16398us; 4us; 32768us; 4us; 32us; 12us; 9us; 14us; 10us; 15us; 8us; 0us; 16399us; 1us; 32768us; 16us; 27us; 3us; 32768us; 0us; 3us; 1us; 4us; 2us; 5us; 0us; 16400us; 1us; 32768us; 16us; 30us; 4us; 32768us; 4us; 32us; 12us; 9us; 14us; 10us; 15us; 8us; 0us; 16401us; 10us; 32768us; 6us; 14us; 7us; 17us; 8us; 19us; 9us; 21us; 10us; 24us; 11us; 26us; 12us; 9us; 13us; 29us; 14us; 10us; 15us; 8us; 1us; 32768us; 5us; 34us; 0us; 16402us; 2us; 32768us; 3us; 37us; 4us; 32us; 0us; 16403us; 0us; 16404us; |]
let _fsyacc_actionTableRowOffsets = [|0us; 3us; 4us; 5us; 6us; 7us; 11us; 15us; 16us; 17us; 18us; 19us; 20us; 21us; 22us; 27us; 32us; 33us; 38us; 39us; 44us; 45us; 50us; 55us; 56us; 61us; 62us; 64us; 68us; 69us; 71us; 76us; 77us; 88us; 90us; 91us; 94us; 95us; |]
let _fsyacc_reductionSymbolCounts = [|1us; 1us; 1us; 1us; 3us; 1us; 1us; 1us; 1us; 1us; 1us; 3us; 2us; 2us; 3us; 2us; 3us; 3us; 3us; 2us; 1us; |]
let _fsyacc_productionToNonTerminalTable = [|0us; 1us; 2us; 2us; 2us; 3us; 3us; 3us; 4us; 4us; 5us; 5us; 5us; 5us; 5us; 5us; 5us; 5us; 6us; 7us; 7us; |]
let _fsyacc_immediateActions = [|65535us; 49152us; 16385us; 16386us; 16387us; 65535us; 65535us; 16388us; 16389us; 16390us; 16391us; 16392us; 16393us; 16394us; 65535us; 65535us; 16395us; 65535us; 16396us; 65535us; 16397us; 65535us; 65535us; 16398us; 65535us; 16399us; 65535us; 65535us; 16400us; 65535us; 65535us; 16401us; 65535us; 65535us; 16402us; 65535us; 16403us; 16404us; |]
let _fsyacc_reductions ()  =    [| 
# 188 "Parser.fs"
        (fun (parseState : FSharp.Text.Parsing.IParseState) ->
            let _1 = (let data = parseState.GetInput(1) in (Microsoft.FSharp.Core.Operators.unbox data : AST.Prog)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
                      raise (FSharp.Text.Parsing.Accept(Microsoft.FSharp.Core.Operators.box _1))
                   )
                 : '_startstart));
# 197 "Parser.fs"
        (fun (parseState : FSharp.Text.Parsing.IParseState) ->
            let _1 = (let data = parseState.GetInput(1) in (Microsoft.FSharp.Core.Operators.unbox data : 'prog)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 14 "Parser.fsy"
                                   _1 
                   )
# 14 "Parser.fsy"
                 : AST.Prog));
# 208 "Parser.fs"
        (fun (parseState : FSharp.Text.Parsing.IParseState) ->
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 19 "Parser.fsy"
                                Type.Nat 
                   )
# 19 "Parser.fsy"
                 : 'typ));
# 218 "Parser.fs"
        (fun (parseState : FSharp.Text.Parsing.IParseState) ->
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 20 "Parser.fsy"
                                 Type.Atom 
                   )
# 20 "Parser.fsy"
                 : 'typ));
# 228 "Parser.fs"
        (fun (parseState : FSharp.Text.Parsing.IParseState) ->
            let _2 = (let data = parseState.GetInput(2) in (Microsoft.FSharp.Core.Operators.unbox data : 'typ)) in
            let _3 = (let data = parseState.GetInput(3) in (Microsoft.FSharp.Core.Operators.unbox data : 'typ)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 21 "Parser.fsy"
                                         Type.Pair(_2,_3) 
                   )
# 21 "Parser.fsy"
                 : 'typ));
# 240 "Parser.fs"
        (fun (parseState : FSharp.Text.Parsing.IParseState) ->
            let _1 = (let data = parseState.GetInput(1) in (Microsoft.FSharp.Core.Operators.unbox data : string)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 25 "Parser.fsy"
                                Atom(_1) 
                   )
# 25 "Parser.fsy"
                 : 'value));
# 251 "Parser.fs"
        (fun (parseState : FSharp.Text.Parsing.IParseState) ->
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 26 "Parser.fsy"
                                Nat(0u) 
                   )
# 26 "Parser.fsy"
                 : 'value));
# 261 "Parser.fs"
        (fun (parseState : FSharp.Text.Parsing.IParseState) ->
            let _1 = (let data = parseState.GetInput(1) in (Microsoft.FSharp.Core.Operators.unbox data : uint32)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 27 "Parser.fsy"
                               Nat(_1) 
                   )
# 27 "Parser.fsy"
                 : 'value));
# 272 "Parser.fs"
        (fun (parseState : FSharp.Text.Parsing.IParseState) ->
            let _1 = (let data = parseState.GetInput(1) in (Microsoft.FSharp.Core.Operators.unbox data : 'stmnt)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 30 "Parser.fsy"
                                 _1 
                   )
# 30 "Parser.fsy"
                 : 'both));
# 283 "Parser.fs"
        (fun (parseState : FSharp.Text.Parsing.IParseState) ->
            let _1 = (let data = parseState.GetInput(1) in (Microsoft.FSharp.Core.Operators.unbox data : 'value)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 31 "Parser.fsy"
                                 _1 
                   )
# 31 "Parser.fsy"
                 : 'both));
# 294 "Parser.fs"
        (fun (parseState : FSharp.Text.Parsing.IParseState) ->
            let _1 = (let data = parseState.GetInput(1) in (Microsoft.FSharp.Core.Operators.unbox data : 'value)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 35 "Parser.fsy"
                                _1
                   )
# 35 "Parser.fsy"
                 : 'stmntbody));
# 305 "Parser.fs"
        (fun (parseState : FSharp.Text.Parsing.IParseState) ->
            let _2 = (let data = parseState.GetInput(2) in (Microsoft.FSharp.Core.Operators.unbox data : 'both)) in
            let _3 = (let data = parseState.GetInput(3) in (Microsoft.FSharp.Core.Operators.unbox data : 'both)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 36 "Parser.fsy"
                                          Cons(_2, _3) 
                   )
# 36 "Parser.fsy"
                 : 'stmntbody));
# 317 "Parser.fs"
        (fun (parseState : FSharp.Text.Parsing.IParseState) ->
            let _2 = (let data = parseState.GetInput(2) in (Microsoft.FSharp.Core.Operators.unbox data : 'both)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 37 "Parser.fsy"
                                     Car(_2) 
                   )
# 37 "Parser.fsy"
                 : 'stmntbody));
# 328 "Parser.fs"
        (fun (parseState : FSharp.Text.Parsing.IParseState) ->
            let _2 = (let data = parseState.GetInput(2) in (Microsoft.FSharp.Core.Operators.unbox data : 'both)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 38 "Parser.fsy"
                                     Cdr(_2) 
                   )
# 38 "Parser.fsy"
                 : 'stmntbody));
# 339 "Parser.fs"
        (fun (parseState : FSharp.Text.Parsing.IParseState) ->
            let _2 = (let data = parseState.GetInput(2) in (Microsoft.FSharp.Core.Operators.unbox data : 'both)) in
            let _3 = (let data = parseState.GetInput(3) in (Microsoft.FSharp.Core.Operators.unbox data : 'both)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 39 "Parser.fsy"
                                           Plus( _2, _3) 
                   )
# 39 "Parser.fsy"
                 : 'stmntbody));
# 351 "Parser.fs"
        (fun (parseState : FSharp.Text.Parsing.IParseState) ->
            let _2 = (let data = parseState.GetInput(2) in (Microsoft.FSharp.Core.Operators.unbox data : 'both)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 40 "Parser.fsy"
                                      Add1(_2) 
                   )
# 40 "Parser.fsy"
                 : 'stmntbody));
# 362 "Parser.fs"
        (fun (parseState : FSharp.Text.Parsing.IParseState) ->
            let _2 = (let data = parseState.GetInput(2) in (Microsoft.FSharp.Core.Operators.unbox data : string)) in
            let _3 = (let data = parseState.GetInput(3) in (Microsoft.FSharp.Core.Operators.unbox data : 'typ)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 41 "Parser.fsy"
                                          Claim (_2,_3) 
                   )
# 41 "Parser.fsy"
                 : 'stmntbody));
# 374 "Parser.fs"
        (fun (parseState : FSharp.Text.Parsing.IParseState) ->
            let _2 = (let data = parseState.GetInput(2) in (Microsoft.FSharp.Core.Operators.unbox data : string)) in
            let _3 = (let data = parseState.GetInput(3) in (Microsoft.FSharp.Core.Operators.unbox data : 'both)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 42 "Parser.fsy"
                                            Define ( _2, _3) 
                   )
# 42 "Parser.fsy"
                 : 'stmntbody));
# 386 "Parser.fs"
        (fun (parseState : FSharp.Text.Parsing.IParseState) ->
            let _2 = (let data = parseState.GetInput(2) in (Microsoft.FSharp.Core.Operators.unbox data : 'stmntbody)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 46 "Parser.fsy"
                                                     _2 
                   )
# 46 "Parser.fsy"
                 : 'stmnt));
# 397 "Parser.fs"
        (fun (parseState : FSharp.Text.Parsing.IParseState) ->
            let _1 = (let data = parseState.GetInput(1) in (Microsoft.FSharp.Core.Operators.unbox data : 'stmnt)) in
            let _2 = (let data = parseState.GetInput(2) in (Microsoft.FSharp.Core.Operators.unbox data : 'prog)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 51 "Parser.fsy"
                                      List.rev (_1::_2) 
                   )
# 51 "Parser.fsy"
                 : 'prog));
# 409 "Parser.fs"
        (fun (parseState : FSharp.Text.Parsing.IParseState) ->
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 52 "Parser.fsy"
                               [] 
                   )
# 52 "Parser.fsy"
                 : 'prog));
|]
# 420 "Parser.fs"
let tables () : FSharp.Text.Parsing.Tables<_> = 
  { reductions= _fsyacc_reductions ();
    endOfInputTag = _fsyacc_endOfInputTag;
    tagOfToken = tagOfToken;
    dataOfToken = _fsyacc_dataOfToken; 
    actionTableElements = _fsyacc_actionTableElements;
    actionTableRowOffsets = _fsyacc_actionTableRowOffsets;
    stateToProdIdxsTableElements = _fsyacc_stateToProdIdxsTableElements;
    stateToProdIdxsTableRowOffsets = _fsyacc_stateToProdIdxsTableRowOffsets;
    reductionSymbolCounts = _fsyacc_reductionSymbolCounts;
    immediateActions = _fsyacc_immediateActions;
    gotos = _fsyacc_gotos;
    sparseGotoTableRowOffsets = _fsyacc_sparseGotoTableRowOffsets;
    tagOfErrorTerminal = _fsyacc_tagOfErrorTerminal;
    parseError = (fun (ctxt:FSharp.Text.Parsing.ParseErrorContext<_>) -> 
                              match parse_error_rich with 
                              | Some f -> f ctxt
                              | None -> parse_error ctxt.Message);
    numTerminals = 20;
    productionToNonTerminalTable = _fsyacc_productionToNonTerminalTable  }
let engine lexer lexbuf startState = (tables ()).Interpret(lexer, lexbuf, startState)
let start lexer lexbuf : AST.Prog =
    Microsoft.FSharp.Core.Operators.unbox ((tables ()).Interpret(lexer, lexbuf, 0))
